version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: email
      PGADMIN_DEFAULT_PASSWORD: password2
    ports:
      - "8090:80" #"8080:80"
    depends_on:
      - db
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    